#!/usr/bin/env python
import redis
import time

client = redis.Redis('localhost')

t0 = time.time()
pipe = client.pipeline(transaction=False)
for x in xrange(100):
  for i in xrange(50000):
    pipe.hincrby( str(x), i, 1 )
    if i%1000==0: pipe.execute()
pipe.execute()
t1 = time.time()

pipe = client.pipeline(transaction=False)
for x in xrange(10,40):
  pipe.hgetall( str(x) )

t2 = time.time()
res = pipe.execute()
t3 = time.time()

rval = {}
for x,data in enumerate(res):
  rval[x] = data
t4 = time.time()

print t1-t0, t2-t1, t3-t2, t4-t3
print len(rval)

client.flushdb()
